Azael
FbW36/39-PB-datastructure-nesting pull request #9
Opened 2020-11-09 13:56 UTC by Zarzarius

2020-11-10 10:50 UTC, ciamac-da requested changes

2020-11-10 10:50 UTC, ciamac-da commented on Azael/app.js
>    myMethod: function print() {
2-4 ==> line 32 your function is myMethod and not print, therefore you have to get rid of print 
Then after doggo object in line 36 you can call the function using doggo.myMethod()

2020-11-10 19:42 UTC, Zarzarius reviewed
Get rid of Function Print

2020-11-11 07:53 UTC, ciamac-da approved these changes

2020-11-11 07:53 UTC, merged